server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_software?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  servlet:
    multipart:
      max-file-size: 100MB # 요청한 파일 한 개의 크기
      max-request-size: 100MB # 요청한 파일 전체의 크기
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # swagger 설정
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #하이버네이트 대문자 전략
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect

#cloud:
#    s3:
#    # bucket:  # 버킷명 , S3 DetailInfo 에 저장
#    region:
#      static: ap-northeast-2 # 리전
#    stack:
#      auto: false # Spring Cloud는 환경 또는 스택을 기반으로 이를 자동으로 감지
#


logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
    #            sql:
